# Site settings
title: Zack Li
description: 'graduate student in astrophysics at Princeton'
url: 'zack.li'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Zack Li'
  email: zq@princeton.edu
  twitter_username:  
  facebook_username: xzackli
  github_username:  xzackli
  linkedin_username:  zequnli

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

collections:
  logs:
    output: true
    
