# Site settings

title: Zack Li # Title of your site
email: zq@princeton.edu # Your contact email

description: > # this means to ignore newlines until "baseurl:"
  Graduate student in astrophysics at Princeton.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zack.li" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:       # Replace this with your Twitter username
github_username:      xzackli  # Replace this with your GitHub username
linkedin_username:      # Replace this with your LinkedIn username
google_plus_username:   # Replace this with your Google+ username
facebook_username:    xzackli  # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username

# Build settings
markdown: kramdown
